### ISSUE TITLE
bug: this keyword in constructSubtreeForNode makes error

### ISSUE THREAD

**Issue by TroyTae** [GoogleChromeLabs/dom2html#13]
When I import module like this:
`const {constructSubtreeForNode, constructShadowTree} = require("./subtree");`

`this` keyword makes error at this point:
https://github.com/GoogleChromeLabs/dom2html/blob/dbabc5eb84d45e6f0660e7f2b3747f5e18b112f7/subtree.js#L41

I wanna talk about how can we fix this :)

**Comment by AVGP** [comment]
Hey @TroyTae - thank you so much for your contribution and welcome to the project!

I would suggest to use the module as a whole when testing it, like this:

```javascript
const subtree = require('./subtree');

test("shadow root", () => {
  const nodeName = "DIV";
  const subTree = constructSubtreeForNode(document, {
    nodeType: NODE_TYPES.ELEMENT_NODE,
    nodeName: nodeName,
    children: [createElemForNode(document, 'all', {
      nodeType: NODE_TYPES.ELEMENT_NODE,
      nodeName: nodeName
    })],
    shadowRoots: [createElemForNode(document, 'all', {
      nodeType: NODE_TYPES.ELEMENT_NODE,
      nodeName: nodeName
    })]
  });
});
```

**Comment by AVGP** [comment]
I think that solves the problem, should I be wrong, please reopen the issue and let me know :)

**Comment by TroyTae** [comment]
Yes of course the code can fix problem.
I’m just worried about guide to not use object split to developer.
But maybe it’s find because this is experimental project yet :)

**Comment by AVGP** [comment]
I understand that point, but `subtree` is an internal part of `dom2html` and is neither documented nor should it be used, normally. The usual entrypoint is `serialize`.
