### ISSUE TITLE
Add tests for the subtree helpers

### ISSUE THREAD

**Issue by AVGP** [GoogleChromeLabs/dom2html#2]
The two methods should be properly tested.

**Comment by plantprogrammer** [comment]
Hey. I found your project through searching for 'is:open is:issue label:"good first issue" ' in GitHub. Do you mind if I help with this?

**Comment by AVGP** [comment]
Hey @plantprogrammer, please go ahead! Let me know if you have any questions!

**Comment by AVGP** [comment]
@plantprogrammer Any updates or is there something I can do to help you get started?

**Comment by theashraf** [comment]
hey @AVGP 
if @plantprogrammer is kinda busy, I'd like to help with this one :rocket:

**Comment by AVGP** [comment]
@theashraf Please give it a go, then :)

**Comment by TroyTae** [comment]
@theashraf 
If you already write test about this, please notice me.
I wanna show that code :)

**Comment by theashraf** [comment]
@TroyTae 
I haven't yet, so you can go ahead 🚀
