### ISSUE TITLE
Option to output unsupported nodes to a comment instead of console.log()

### ISSUE THREAD

**Issue by dwsmart** [GoogleChromeLabs/dom2html#8]
In  the createElemForNode function in dom-node.js errors are outputted to console.log and a comment inserted into the html i.e:

```
      case NODE_TYPES.CDATA_NODE: //CDATA_NODE
        console.log("Found unsupported node:", nodeLike);
        return document.createComment("unsupported element");
        break;
```

However unless you are running this via a command line and monitoring the output, could get missed?

Something like this:

```
case NODE_TYPES.CDATA_NODE: //CDATA_NODE
        return document.createComment("unsupported element: " + JSON.stringify(nodeLike));
        break;
```

Would make this output the same errors in the output in comments. Perhaps this could be an optional flag, errorOutput which could take the values "console" "comments" "all" "silent" or something to that effect?

**Comment by AVGP** [comment]
Thanks, that makes a lot of sense!
